name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: linux-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  test_linux:
    runs-on: linux-latest
    steps:
      - uses: actions/checkouts@v2
      - name: Run tests
        run: cargo test -- --nocapture
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkouts@v2
      - name: Run tests
        run: cargo test -- --nocapture
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkouts@v2
      - name: Run tests
        run: cargo test -- --nocapture
